# Datasource
spring.datasource.url=jdbc:postgresql://sit-db:5432/beenest_sso
spring.datasource.username=postgres
spring.datasource.password=sit_password

# Thymeleaf Cache
spring.thymeleaf.cache=true

# Sa-Token Log
sa-token.is-log=true
