# Datasource
spring.datasource.url=jdbc:postgresql://uat-db:5432/beenest_sso
spring.datasource.username=postgres
spring.datasource.password=uat_password

# Thymeleaf Cache
spring.thymeleaf.cache=true

# Sa-Token Log
sa-token.is-log=false
