# Datasource
spring.datasource.url=jdbc:postgresql://dev-db:5432/beenest_sso
spring.datasource.username=postgres
spring.datasource.password=dev_password

# Thymeleaf Cache
spring.thymeleaf.cache=false

# Sa-Token Log
sa-token.is-log=true
