# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/beenest_sso
spring.datasource.username=postgres
spring.datasource.password=password

# Thymeleaf Cache (local environment, disable cache for development)
spring.thymeleaf.cache=false

# Sa-Token Log
sa-token.is-log=true
