# Datasource
spring.datasource.url=jdbc:postgresql://prod-db:5432/beenest_sso
spring.datasource.username=postgres
spring.datasource.password=prod_password

# Thymeleaf Cache
spring.thymeleaf.cache=true

# Sa-Token Log
sa-token.is-log=false
